spring:
  application.name: auth-service
  datasource:
    hikari.maximum-pool-size: 8
  jpa:
    defer-datasource-initialization: true
logging:
  level:
    root: info
    org.hibernate.SQL: info
server:
  port: 8079