services:
  patient-service:
    build: ./patient-service
    container_name: patient-service
    image: patient-service:latest
    pull_policy: never
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - patient-network
    depends_on:
      postgres-db:
        condition: service_healthy

  billing-service:
    build: ./billing-service
    container_name: billing_service
    image: billing-service:latest
    pull_policy: never
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
      - "9091:9091"
    networks:
      - patient-network

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    image: analytics-service:latest
    pull_policy: never
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8082:8082"
    networks:
      - patient-network

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    image: appointment-service:latest
    pull_policy: never
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8083:8083"
    networks:
      - patient-network
    depends_on:
      appointment-postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:17.6
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - patient-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  appointment-postgres-db:
    image: postgres:17.6
    restart: always
    env_file:
      - .env
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${APPOINTMENT_POSTGRES_DB}
    volumes:
      - appointment_pgdata:/var/lib/postgresql/data
    networks:
      - patient-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${APPOINTMENT_POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    env_file:
      - .env
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - patient-network
    depends_on:
      postgres-db:
        condition: service_started

volumes:
  pgdata:
  pgadmin-data:
  appointment_pgdata:

networks:
  patient-network:
    driver: bridge
    external: true