server:
  port: 7950
# todo: Eureka / Discovery Client
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route http://localhost:7950/auth/login -> Api Gateway intercept --> http://localhost:7950/login
            - id: auth-service-routr
              uri: http://auth-service:8079
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            # Route for /api/patients/** to patient-service
            - id: patient-service-route
              uri: http://patient-service:8080
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            # Route for /api/docs/patients to patient-service /v3/api-docs
            - id: api-docs-patient-service
              uri: http://patient-service:8080
              predicates:
                - Path=/api-docs/patients/
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs