services:
  auth-postgres-db:
    image: postgres:17.6
    restart: always
    env_file:
      - .env
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - patient-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${AUTH_POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  auth_pgdata:

networks:
  patient-network:
    external: true