services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml # single file config bind mount
      - prometheus-data:/prometheus # named volume managed by docker -> docker volume inspect
      #- ./prometheus-data:/prometheus # bind mount host catalog to container /prometheus
    ports:
      - "9090:9090"
    networks:
      - patient-network

networks:
  patient-network:
    external: true

volumes:
  prometheus-data:
