spring:
  config.activate.on-profile: staging
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      properties.hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # validate, schema managing migration tool
    show-sql: true # false
  sql.init.mode: always # never
logging:
  level:
    org.springframework: info
    root: info
    org.hibernate.SQL: info
server:
  port: 8081