spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: postgres
    password: admin
  jpa:
    properties:
      properties.hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql.init.mode: always
logging:
  level:
    root: info
    org.hibernate.SQL: debug
server:
  port: 8080