spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
server:
  port: 8080