name: CI test
on:
  push:
  pull_request:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24
          cache: maven
      - name: Build and run tests (patient-service)
        run: mvn -f patient-service/pom.xml test -Dtest=PatientServiceApplicationTests